# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

In [3]:
arr = np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
list_1 = list(map(int,input('Enter 5 numbers for list 1 (separate them with space) : ').strip().split()))[:5] 
list_2 = list(map(int,input('Enter 5 numbers for list 2 (separate them with space) : ').strip().split()))[:5]

array_1 = np.array(list_1)
array_2 = np.array(list_2)

con_array = np.concatenate((array_1,array_2))
print("Concatenate array : - ",con_array)
print("Sort Concatenate array: - ",np.sort(con_array))

Enter 5 numbers for list 1 (separate them with space) : 5 1 7 8 9  
Enter 5 numbers for list 2 (separate them with space) : 8 9 2 3 7 
Concatenate array : -  [5 1 7 8 9 8 9 2 3 7]
Sort Concatenate array: -  [1 2 3 5 7 7 8 8 9 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.


In [5]:
arr_1 = np.arange(12)
print(arr_1)
print('The dimention of the array :', arr_1.ndim)
print('Size of the array:', arr_1.size)

#I find the dimentions and the sie of the array by using numpy 'nd'

[ 0  1  2  3  4  5  6  7  8  9 10 11]
The dimention of the array : 1
Size of the array: 12


In [6]:
arr_2 = np.arange(12).reshape((3,4))
print(arr_2)
print('The dimention of the array :', arr_2.ndim)
print('Size of the array:', arr_2.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The dimention of the array : 2
Size of the array: 12


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [8]:
arr_1_dim = np.array([2,4,8,9,7,8,7,8,6])
print(arr_1_dim)
print('The dimentions of the array is: ', arr_1_dim.ndim)
#wI can use the np.newaxis to increase the dimesions in a array
# Using np.newaxis will increase the dimensions of your array by one dimension when used once. 

[2 4 8 9 7 8 7 8 6]
The dimentions of the array is:  1


In [9]:
arr_2_dim = arr_1_dim[np.newaxis, :]
print("The dimentions of the array: ",arr_2_dim.ndim)

The dimentions of the array:  2


In [10]:
arr_1_dim

array([2, 4, 8, 9, 7, 8, 7, 8, 6])

In [11]:
arr2_2_dim = np.expand_dims(arr_1_dim, axis=0)
print(arr2_2_dim)
print("The dimentions of the array: ",arr2_2_dim.ndim)

# we can also expand an array by inserting a new axis at a specified position with np.expand_dims.

[[2 4 8 9 7 8 7 8 6]]
The dimentions of the array:  2


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [12]:
sqr_mat_1 = np.arange(1,17).reshape((4,4))
sqr_mat_2 = np.arange(18,34).reshape((4,4))
print('sqr_mat_1: ')
print(sqr_mat_1)
print('\n')
print('sqr_mat_2: ')
print(sqr_mat_2)

sqr_mat_1: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


sqr_mat_2: 
[[18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [13]:
#using vstack() i can join two matrix vertically
print('Using vstck() to append two matrix vertically: ')
print('\n')
print( np.vstack((sqr_mat_1,sqr_mat_2)))

Using vstck() to append two matrix vertically: 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [14]:
#using htack() i can join two matrix horizontally

print('Using hstack() to join two matrix horizontally:')
print('\n')
print(np.hstack((sqr_mat_1,sqr_mat_2)))

Using hstack() to join two matrix horizontally:


[[ 1  2  3  4 18 19 20 21]
 [ 5  6  7  8 22 23 24 25]
 [ 9 10 11 12 26 27 28 29]
 [13 14 15 16 30 31 32 33]]


# Questions 6:
How to get unique items and counts of unique items?

In [15]:
#i can use python "set()" to get unique item from list,

list_num = [10, 20, 55, 88, 10, 66, 20, 88, 10, 55]
#here a list of avengers charcaters name. and some name is repeated. 
# i can use python unique method to get unique charecters name with no repetitons
set_list = list(set(list_num))
print('Original list: ', list_num)
print('Unique item from the list', set_list)
print('Length of the unique list (it is the same as how many unique items are there): ', len(set_list))



Original list:  [10, 20, 55, 88, 10, 66, 20, 88, 10, 55]
Unique item from the list [66, 10, 20, 55, 88]
Length of the unique list (it is the same as how many unique items are there):  5


In [16]:
#there is another and more easy way to get unique item from a list that is pandas unique() method to get unique items
# nunique() method - to get number of unique items, but for that I need to import pandas and convert list in to Series

import pandas as pd
ser = pd.Series(list_num)
print('The series: ', ser)
print('Unique item in the series: ', ser.unique())
print('Number of unique items', ser.nunique())

The series:  0    10
1    20
2    55
3    88
4    10
5    66
6    20
7    88
8    10
9    55
dtype: int64
Unique item in the series:  [10 20 55 88 66]
Number of unique items 5
